### ISSUE TITLE
Cannot find module '@ca11/webphone-theme/icons/index.js'

### ISSUE THREAD

**Issue by jbreitung** [garage11/ca11#8]
Hi, I'm trying to install your package with the help of the readme you provided.

At the point I'm trying to run "yarn" it aborts after some time with the following error message:
Cannot find module '@ca11/webphone-theme/icons/index.js'

The complete log output is the following:

```
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
$ snowpack --include "packages/webphone/**/*.js" --dest build/static/web_modules
⠼ snowpack installing... @ca11/sig11/lib/crypto.js, @ca11/sig11/lib/endpoint.js, @ca11/sig11/lib/network.js, @ca11/webphone-theme/icons/index.js
✖ Cannot find module '@ca11/webphone-theme/icons/index.js'
Require stack:
- /var/local/ca11/node_modules/snowpack/dist-node/index.js
- /var/local/ca11/node_modules/snowpack/dist-node/index.bin.js
⚠ Finished with warnings.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by jvanveen** [comment]
Hi there,

Sorry for the late response. I totally missed the issue.
As you've noticed, everything is still in a very early/broken state. I think the install process
is getting better though. Lerna was recently replaced with yarn workspaces. I think this 
solves the particular issue. The webphone-theme package is supposed to come from 
packages/webphone-theme; not from npm. I tried a clean yarn install and the install now 
appears to work. Hope it helps.

Cheers,

Jeroen
